engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
  fixme:
    enabled: true
  tslint:
    config: tslint.json
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- "hooks/"
- "screenshots/"
- "resources/"