language: android

sudo: false

node_js:
  -"4.1"

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

before_install:
  - nvm install v4
  - npm i -g npm@^2.0.0
  - npm install -g cordova ionic@beta

install:
  - npm install
  - ionic platform add android
  - cordova prepare
  - npm run webdriver-update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - export TS_NODE_DISABLE_WARNINGS=false
  - ionic build android
  - npm test
  - npm run coverage

notifications:
  email:
    recipients:
      - henrique.dias@alientronics.com.br
    on_success: change
    on_failure: always