language: android

sudo: required
node_js:
  -"4.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
  code_climate:
    repo_token: 07f0186ba388873f07c7e0e530c98e720277303f54bbc4f9be87d2f99e203272

android:
  components:
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository 
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23

before_install:
  - nvm install stable
  - npm install -g npm
  - npm install -g cordova ionic

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ionic platform add android
  - ionic state restore
  - ionic build android
  - npm test

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    recipients:
      - henrique@alientronics.com.br
    on_success: change
    on_failure: always
