language: android

sudo: false

node_js:
  -"4.1"

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23

before_install:
  - nvm install v4
  - npm i -g npm@^2.0.0
  - npm install -g cordova ionic@beta

install:
  - npm install
  - ionic platform add android
  - cordova plugin add cordova-plugin-googleplus
  - ionic plugin add cordova-plugin-geolocation
  - cordova prepare

script:
  - ionic build android