language: android

sudo: required
node_js:
  -"4.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome

android:
  components:
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository 
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23

before_install:
  - nvm install stable
  - npm install -g npm
  - npm install -g cordova ionic

install:
  - npm install
  - ionic platform add android
  - ionic state restore

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export TS_NODE_DISABLE_WARNINGS=false

script:
  - ionic build android
  - npm test

notifications:
  email:
    recipients:
      - henrique.dias@alientronics.com.br
    on_success: change
    on_failure: always
